services:
  - type: web
    name: advayx-builder
    plan: free
    env: node
    buildCommand: |
      # 1. Install Cordova
      npm install -g cordova
      
      # 2. Create Cordova project
      cordova create AdvayX com.advayx AdvayX
      cd AdvayX
      
      # 3. Add Android platform (minimal setup)
      cordova platform add android --nofetch
      
      # 4. Build APK (debug mode for speed)
      cordova build android --no-update-notifier --debug
      
      # 5. Move APK to root for download
      cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../
      
      # 6. Return to root (critical for server.js)
      cd ..
    startCommand: node server.js  # Required to keep service alive
    healthCheckPath: /health       # Required for free tier
